version: '3.8'

services:
  sqlserver:
    container_name: sqlserver_container
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      SA_PASSWORD: "Akjd3_as77"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

    volumes:
      - sql_data:/var/opt/mssql
      - ./init-db:/usr/src/app


volumes:
  sql_data:

networks:
  backend:
    driver: bridge